# Default config
$site = "ftp://ucmirror.canterbury.ac.nz/pub/cygwin/"
$cygdir = "c:\cygwin"

$ErrorActionPreference = "Stop"

# Elevate script if needed
# Get the ID and security principal of the current user account
$myWindowsID = [System.Security.Principal.WindowsIdentity]::GetCurrent()
$myWindowsPrincipal = new-object System.Security.Principal.WindowsPrincipal($myWindowsID)

# Get the security principal for the Administrator role
$adminRole = [System.Security.Principal.WindowsBuiltInRole]::Administrator

# Check to see if we are currently running "as Administrator"
if (!$myWindowsPrincipal.IsInRole($adminRole))
{
   # Relaunch as administrator

   # Create a new process object that starts PowerShell
   $newProcess = new-object System.Diagnostics.ProcessStartInfo "PowerShell";

   # Specify the current script path and name as a parameter
   $newProcess.Arguments = "-ExecutionPolicy Unrestricted " + $script:MyInvocation.MyCommand.Path

   Write-Host $newProcess.Arguments

   # Indicate that the process should be elevated
   $newProcess.Verb = "runas";

   # Start the new process
   [System.Diagnostics.Process]::Start($newProcess);

   # Exit from the current, unelevated, process
   exit
}

# Start actual script

function finish($code)
{
    Write-Host "Press any key to finish..."
    $HOST.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown") | OUT-NULL
    $HOST.UI.RawUI.Flushinputbuffer()
    exit $code
}

function writeHeading($msg)
{
    Write-Host $msg -ForegroundColor Yellow
}

function writeProgress($msg)
{
    Write-Host $msg -ForegroundColor DarkYellow
}

function writeError($msg)
{
    Write-Host $msg -ForegroundColor Red
}

function isReparsePoint([string] $path)
{
    if (!(Test-Path $path)) { return $false }
    $file = Get-Item $path -Force -ea 0
    return [bool] ($file.Attributes -band [IO.FileAttributes]::ReparsePoint)
}

$scriptDir = Split-Path -Parent -Path $MyInvocation.MyCommand.Definition
# Cygwin home directory
$username = $Env:USERNAME
$cyghome = Join-Path $cygdir "home\$username"
$localBashrcWrapper = Join-Path $cyghome ".bashrc"

function isHomeDirLinked($createBashrcBackup)
{
    $localFileBak = $localBashrcWrapper + ".cebak"
    if (Test-Path $localBashrcWrapper)
    {
        if (Test-Path $localFileBak)
        {
            return $true
        }

        $fileContent = @(Get-Content $localBashrcWrapper)
        if ($fileContent)
        {
            $topLine = $fileContent[0]
            if ($topLine -like "*cygenv*")
            {
                return $true
            }
        }

        if ($createBashrcBackup)
        {
            Move-Item $localBashrcWrapper $localFileBak
        }
    }

    return $false
}

# Symlink Cygwin home to Windows Home
function linkHomeDir()
{
    # Check if we've already done it before
    if (isReparsePoint $cyghome) { return }
    if (isHomeDirLinked $false) { return }
    $homeDirBak = $cyghome + ".cebak"
    if (Test-Path $homeDirBak) { return }

    # Not been symlinked
    writeHeading "Symlink Cygwin home to Windows Home"
    $realHomeDir = ""

    # Determine if Windows home path is mapped remote
    if (Test-Path Env:\HOMESHARE)
    {
        $realHomeDir = $Env:HOMESHARE
    }
	else
	{
		$realHomeDir = Join-Path $Env:HOMEDRIVE $Env:HOMEPATH
	}

    if (!(Test-Path $realHomeDir)) { return }
    writeProgress "Windows Home is $realHomeDir"
    if (Test-Path $cyghome)
    {
        Move-Item $cyghome $homeDirBak
    }
    cmd.exe /c mklink /d $cyghome $realHomeDir

    Copy-Item (Join-Path $scriptDir ".inputrc") $cyghome

    Copy-Item (Join-Path $scriptDir ".profile") $cyghome
}

function createBashrcWrapper()
{
    if (isHomeDirLinked $true) { return }

    $cygenvFile = Join-Path $scriptDir ".bashrc"
	writeProgress "Creating .bashrc wrapper back to $cygenvFile"
    $text = "# cygenv wrapper. Do not edit this file, use ~/bashrc_custom instead.`nif [ `$OSTYPE = `"cygwin`" ]; then`n    . ``cygpath `"$cygenvFile`"```nfi"
    # Ridiculousness due to PS cmdlets adding CRLF when writing to files
    [io.file]::WriteAllText($localBashrcWrapper, $text)

    $bashrcCustom = Join-Path $scriptDir "bashrc_custom"
    $text = "# Add your custom .bashrc commands here"
    # Ridiculousness due to PS cmdlets adding CRLF when writing to files
    [io.file]::WriteAllText($bashrcCustom, $text)
}

$setupDir = Join-Path $cygdir "setup"
$setupProg = Join-Path $setupDir "setup-x86.exe"

$upgrading = Test-Path (Join-Path $cygdir "bin")

if ($upgrading)
{
    writeHeading "Upgrade started"
}
else
{
    writeHeading "Fresh install started"
}

try
{
    if (!(Test-Path $setupDir)) { md $setupDir }
    writeProgress "Fetching latest Cygwin installer"
    $wc = New-Object System.Net.WebClient
    $wc.DownloadFile("http://cygwin.com/setup-x86.exe", $setupProg)

    pushd .
    chdir $setupDir
    $args = "-q -R $cygdir -n -g -o -s $site "
    $args += "--packages openssh,bash,mintty,curl,chere"
    Start-Process -NoNewWindow -Wait $setupProg $args
    popd

    writeHeading "Creating shortcuts"
    $wshShell = New-Object -comObject WScript.Shell
    $lnkArgs = "--hold never -i /Cygwin-Terminal.ico -"

    $desktop =  $wshShell.SpecialFolders.Item("AllUsersDesktop")
    if (!(Test-Path $desktop)) { $desktop = "$Home\Desktop" }
    $lnkFile = Join-Path $desktop "Cygwin Terminal.lnk"
    if (Test-Path $lnkFile)
    {
        writeProgress "Desktop shortcut exists"
        $shortcut = $wshShell.CreateShortcut($lnkFile)
        if ($shortcut.Arguments -ne $lnkArgs)
        {
            writeProgress "Arguments need updating"
            $shortcut.Arguments = $lnkArgs
            $shortcut.Save()
        }
    }
    else
    {
        $shortcut = $wshShell.CreateShortcut($lnkFile)
        $shortcut.TargetPath = Join-Path $cygdir "bin\mintty.exe"
        $shortcut.Arguments = $lnkArgs
        $shortcut.Save()
    }

    $startMenu =  $wshShell.SpecialFolders.Item("AllUsersStartMenu")
    if (!(Test-Path $startMenu)) { $startMenu = "$Home\Start Menu" }
    $startMenuDir = Join-Path $startMenu "Programs\Cygwin"
    $startMenuLnk = Join-Path $startMenuDir "Cygwin Terminal.lnk"
    if (Test-Path $startMenuLnk)
    {
        writeProgress "Start Menu shortcut exists"
        $shortcut = $wshShell.CreateShortcut($startMenuLnk)
        if ($shortcut.Arguments -ne $lnkArgs)
        {
            writeProgress "Arguments need updating"
            $shortcut.Arguments = $lnkArgs
            $shortcut.Save()
        }
    }
    else
    {
        if (!(Test-Path $startMenuDir)) { mkdir -p $startMenuDir }
        Copy-Item $lnkFile $startMenuLnk
    }

    linkHomeDir
    createBashrcWrapper

    $minttyrc = Join-Path $cyghome ".minttyrc"
    if (!(Test-Path $minttyrc))
    {
        $minttyrcRepo = Join-Path $scriptDir ".minttyrc"
        writeProgress "Copying default mintty config"
        Copy-Item $minttyrcRepo $minttyrc
    }

    writeHeading "Checking for CYGWIN variable"
    if (Test-Path Env:\CYGWIN)
    {
        $value = $Env:CYGWIN
        if ($value -notlike "*nodosfilewarning*")
        {
            $value += " nodosfilewarning"
            writeProgress "Setting value to $value"
            [Environment]::SetEnvironmentVariable("CYGWIN", $value, "Machine")
        }
        else
        {
            writeProgress "Variable already set"
        }
    }
    else
    {
        writeProgress "Creating variable"
        [Environment]::SetEnvironmentVariable("CYGWIN", "nodosfilewarning", "Machine")
    }

    writeHeading "All done."
    finish 0
}
catch
{
    writeError $_.Exception.ToString()
    finish 1
}
